apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-parallel
spec:
  completions: 10
  parallelism: 2
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sleep-container
          image: centos:7
          command: ["sleep"]
          args: ["20"]
      restartPolicy: Never
