apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-never-onfailure
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sleep-container
          image: centos:7
          command: ["sh", "-c"]
          args: ["(sleep 60)"]
      restartPolicy: OnFailure
