apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-oneshot-task
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sleep-container
          image: centos:7
          command: ["sleep"]
          args: ["30"]
      restartPolicy: Never
