apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-multi-workqueue
spec:
  # completions: 1
  parallelism: 3
  backoffLimit: 1
  template:
    metadata:
      name: sleep-job
    spec:
      containers:
        - name: sleep-container
          image: centos:7
          command: ["sleep"]
          args: ["30"]
      restartPolicy: Never
